apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pedidos-api
  template:
    metadata:
      labels:
        app: pedidos-api
    spec:
      containers:
        - name: pedidos-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}