apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "servicio-usuarios-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servicio-usuarios-chart.selectorLabels" . | nindent 10 }}
    spec:
      containers:
        - name: usuarios-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}